# Generated by Django 5.1.5 on 2025-03-09 20:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlassDisposalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='What3words location of disposal bin', max_length=255)),
                ('image', models.ImageField(help_text='photo proof of glass dispolsal', upload_to='glass_disposals/')),
                ('description', models.TextField(help_text='users description of disposed bottles')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('coins_awarded', models.IntegerField(default=0, help_text='coins earned from this disposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
