# Generated by Django 5.1.5 on 2025-03-23 17:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecyclingLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Recycling Bin Name", max_length=255),
                ),
                ("latitude", models.FloatField(help_text="Latitude of recycling bin")),
                (
                    "longitude",
                    models.FloatField(help_text="Longitude of recycling bin"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GlassDisposalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Photo proof of glass disposal",
                        upload_to="glass_disposals/",
                    ),
                ),
                (
                    "bottle_count",
                    models.PositiveIntegerField(help_text="Number of bottles disposed"),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "coins_awarded",
                    models.IntegerField(
                        default=0, help_text="Coins earned from disposal"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recycling_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="glassDisposal.recyclinglocation",
                    ),
                ),
            ],
        ),
    ]
