# Generated by Django 5.1.5 on 2025-03-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glassDisposal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glassdisposalentry',
            name='description',
        ),
        migrations.AddField(
            model_name='glassdisposalentry',
            name='bottle_count',
            field=models.PositiveIntegerField(default=1, help_text='number of bottles handed in'),
        ),
    ]
