# Generated by Django 5.1.5 on 2025-03-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glassDisposal', '0002_remove_glassdisposalentry_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of recycling location ', max_length=255)),
                ('latitude', models.FloatField(help_text='latitude of recycling location')),
                ('longitude', models.FloatField(help_text='longitude of recycling location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
