# Generated by Django 5.1.5 on 2025-03-16 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glassDisposal', '0003_recyclinglocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glassdisposalentry',
            name='location',
        ),
        migrations.AddField(
            model_name='glassdisposalentry',
            name='recycling_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='glassDisposal.recyclinglocation'),
        ),
        migrations.AlterField(
            model_name='glassdisposalentry',
            name='bottle_count',
            field=models.PositiveIntegerField(help_text='Number of bottles disposed'),
        ),
        migrations.AlterField(
            model_name='glassdisposalentry',
            name='coins_awarded',
            field=models.IntegerField(default=0, help_text='Coins earned from disposal'),
        ),
        migrations.AlterField(
            model_name='glassdisposalentry',
            name='image',
            field=models.ImageField(help_text='Photo proof of glass disposal', upload_to='glass_disposals/'),
        ),
        migrations.AlterField(
            model_name='recyclinglocation',
            name='latitude',
            field=models.FloatField(help_text='Latitude of recycling bin'),
        ),
        migrations.AlterField(
            model_name='recyclinglocation',
            name='longitude',
            field=models.FloatField(help_text='Longitude of recycling bin'),
        ),
        migrations.AlterField(
            model_name='recyclinglocation',
            name='name',
            field=models.CharField(help_text='Recycling Bin Name', max_length=255),
        ),
    ]
