# Generated by Django 5.1.6 on 2025-02-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0002_alter_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownscard',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
