# Generated by Django 4.2.19 on 2025-03-21 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0002_alter_challenge_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
