# Generated by Django 4.2.19 on 2025-02-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0003_ownscard_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('packimage', models.ImageField(upload_to='packs/')),
            ],
        ),
    ]
