# Generated by Django 5.1.6 on 2025-02-16 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0003_ownscard_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingchallenge',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
