# Generated by Django 5.1.6 on 2025-02-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0004_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='commonProb',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='pack',
            name='epicProb',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='pack',
            name='legendaryProb',
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name='pack',
            name='rareProb',
            field=models.FloatField(default=0.35),
        ),
    ]
