# Generated by Django 5.1.6 on 2025-02-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0004_ongoingchallenge_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongoingchallenge',
            name='submission',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ongoingchallenge',
            name='submitted_on',
            field=models.DateField(null=True),
        ),
    ]
