# Generated by Django 5.1.6 on 2025-02-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0005_alter_ongoingchallenge_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='worth',
            field=models.IntegerField(default=10),
        ),
    ]
