# Generated by Django 5.1.6 on 2025-02-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0005_pack_commonprob_pack_epicprob_pack_legendaryprob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='color_class',
            field=models.CharField(default='blue', max_length=50),
        ),
    ]
