# Generated by Django 5.1.6 on 2025-02-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0006_challenge_worth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongoingchallenge',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
