# Generated by Django 5.1.5 on 2025-02-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0004_pack'),
        ('EcoWorld', '0007_alter_ongoingchallenge_created_on'),
    ]

    operations = [
    ]
