# Generated by Django 5.1.6 on 2025-02-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0006_pack_color_class'),
        ('EcoWorld', '0007_alter_ongoingchallenge_created_on'),
    ]

    operations = [
    ]
