# Generated by Django 5.1.5 on 2025-02-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0008_merge_20250217_1117'),
        ('EcoWorld', '0008_merge_20250217_1139'),
    ]

    operations = [
    ]
