# Generated by Django 5.1.5 on 2025-02-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EcoWorld", "0009_waterbottlefill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drinkevent",
            name="drank_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
