# Generated by Django 4.2.19 on 2025-03-07 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EcoWorld', '0010_alter_drinkevent_drank_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardID1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CardID1', to='EcoWorld.card')),
                ('cardID2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CardID2', to='EcoWorld.card')),
                ('cardID3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CardID3', to='EcoWorld.card')),
                ('cardID4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CardID4', to='EcoWorld.card')),
                ('cardID5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CardID5', to='EcoWorld.card')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
