# Generated by Django 4.2.19 on 2025-03-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0011_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingchallenge',
            name='completion_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ongoingchallenge',
            name='submitted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
