# Generated by Django 5.1.5 on 2025-03-10 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("EcoWorld", "0011_merge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drinkevent",
            name="fountain",
        ),
        migrations.RemoveField(
            model_name="drinkevent",
            name="user",
        ),
        migrations.RemoveField(
            model_name="waterbottlefill",
            name="user",
        ),
        migrations.DeleteModel(
            name="waterFountain",
        ),
        migrations.DeleteModel(
            name="drinkEvent",
        ),
        migrations.DeleteModel(
            name="WaterBottleFill",
        ),
    ]
