# Generated by Django 5.1.5 on 2025-03-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EcoWorld", "0012_remove_drinkevent_fountain_remove_drinkevent_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ongoingchallenge",
            name="completion_count",
            field=models.IntegerField(default=0),
        ),
    ]
