# Generated by Django 4.2.19 on 2025-03-10 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0013_dailyobjective'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyobjective',
            old_name='progress',
            new_name='current_progress',
        ),
    ]
