# Generated by Django 4.2.19 on 2025-03-10 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0014_rename_progress_dailyobjective_current_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyobjective',
            old_name='current_progress',
            new_name='progress',
        ),
    ]
