# Generated by Django 4.2.19 on 2025-03-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0015_rename_current_progress_dailyobjective_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
