# Generated by Django 4.2.19 on 2025-03-11 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0016_challenge_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyobjective',
            name='last_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
