# Generated by Django 4.2.19 on 2025-03-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0017_dailyobjective_last_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyobjective',
            name='submission',
            field=models.TextField(blank=True, null=True),
        ),
    ]
