# Generated by Django 4.2.19 on 2025-03-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0018_dailyobjective_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyobjective',
            name='coins',
            field=models.IntegerField(default=10),
        ),
    ]
