# Generated by Django 4.2.19 on 2025-03-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0019_dailyobjective_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='goal',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='DailyObjective',
        ),
    ]
