# Generated by Django 4.2.19 on 2025-03-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0020_challenge_goal_delete_dailyobjective'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingchallenge',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
