# Generated by Django 5.1.5 on 2025-03-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_alter_post_challenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="submission",
            field=models.TextField(blank=True, null=True),
        ),
    ]
