# Generated by Django 5.1.5 on 2025-03-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_post_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("challenge", "Challenge Completion"),
                    ("objective", "Daily Objective"),
                    ("card", "Card Achievement"),
                    ("guide", "Guide"),
                ],
                max_length=20,
            ),
        ),
    ]
