# Generated by Django 5.1.6 on 2025-02-06 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWorld', '0001_initial'),
        ('Garden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardensquare',
            name='cardID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EcoWorld.card'),
        ),
    ]
