# Generated by Django 5.1.6 on 2025-02-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garden', '0002_alter_gardensquare_cardid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='size',
            field=models.IntegerField(default=5),
        ),
    ]
