# Generated by Django 5.1.6 on 2025-02-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_of_coins',
            field=models.IntegerField(default=0),
        ),
    ]
