# Generated by Django 5.1.5 on 2025-03-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.TextField(),
        ),
    ]
