# Generated by Django 5.1.5 on 2025-02-04 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Accounts.usertype'),
        ),
    ]
