# Generated by Django 5.1.5 on 2025-02-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.TextField(blank=True),
        ),
    ]
