# Generated by Django 5.1.5 on 2025-02-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_profile_number_of_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.CharField(default='/pfp1.png', max_length=255),
        ),
    ]
