# Generated by Django 4.2.19 on 2025-03-05 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FriendOne', to=settings.AUTH_USER_MODEL)),
                ('userID2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FriendTwo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('userID1', 'userID2')},
            },
        ),
        migrations.CreateModel(
            name='FriendRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiverID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('senderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('senderID', 'receiverID')},
            },
        ),
    ]
