# Generated by Django 5.1.5 on 2025-03-06 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0003_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "permissions": [("can_view_admin_button", "Can grant admin rights")]
            },
        ),
    ]
