# Generated by Django 5.1.5 on 2025-03-10 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0004_alter_profile_options"),
        ("Accounts", "0004_friends_friendrequests"),
    ]

    operations = []
